import type {
  Cambio,
  Cliente,
  Desarrollo,
  Plaza,
  Propuesta,
  Usuario,
} from "./types";

/**
 * Datos de demostración.
 *
 * Los precios, tipologías, esquemas de pago y notas de Playa Park y Real Aurora
 * provienen del análisis real preparado para Berenice y Fabián (septiembre 2026).
 * Lo que no consta en una fuente se deja en `null`: la interfaz lo muestra como
 * [CAMPO] en lugar de inventarlo.
 */

export const HOY = new Date("2026-09-18T12:00:00");

export const plazas: Plaza[] = [
  { id: "riviera-maya", nombre: "Riviera Maya", gerenteId: "u-gerente-rm", activa: true },
  { id: "puebla", nombre: "Puebla", gerenteId: "u-gerente-pue", activa: true },
  { id: "queretaro", nombre: "Querétaro", gerenteId: null, activa: true },
  { id: "vallarta", nombre: "Puerto Vallarta", gerenteId: null, activa: false },
];

export const desarrollos: Desarrollo[] = [
  {
    id: "playa-park",
    nombre: "Playa Park",
    plazaId: "riviera-maya",
    ciudad: "Playa del Carmen",
    zona: null,
    direccion: null,
    mapaUrl: null,
    tipo: "departamento",
    desarrollador: null,
    estatus: "publicado",
    entrega: "Marzo 2027",
    entregaIso: "2027-03",
    responsableId: "u-jorge",
    amenidades: ["Alberca"],
    aConsiderar: ["Las torres no cuentan con elevador, sólo escaleras."],
    tipologias: [
      {
        id: "pp-2hab",
        desarrolloId: "playa-park",
        nombre: "Departamento 2 habitaciones",
        recamaras: 2,
        banos: 2,
        m2Construccion: 91,
        m2Terreno: null,
        estacionamientos: null,
        planoUrl: null,
        niveles: [
          { nombre: "Planta baja", precioLista: 2970000, precioVenta: 2970000, disponibles: null },
          { nombre: "Primer nivel", precioLista: 2790000, precioVenta: 2790000, disponibles: null },
          { nombre: "Segundo nivel", precioLista: 2675000, precioVenta: 2675000, disponibles: null },
          { nombre: "Tercer nivel", precioLista: 2555000, precioVenta: 2555000, disponibles: null },
        ],
      },
      {
        id: "pp-3hab",
        desarrolloId: "playa-park",
        nombre: "Departamento 3 habitaciones",
        recamaras: 3,
        banos: 2,
        m2Construccion: 114,
        m2Terreno: null,
        estacionamientos: null,
        planoUrl: null,
        niveles: [
          { nombre: "Planta baja", precioLista: 3500000, precioVenta: 3500000, disponibles: null },
          { nombre: "Primer nivel", precioLista: 3300000, precioVenta: 3300000, disponibles: null },
          { nombre: "Segundo nivel", precioLista: 3150000, precioVenta: 3150000, disponibles: null },
          { nombre: "Tercer nivel", precioLista: 3070000, precioVenta: 3070000, disponibles: null },
        ],
      },
    ],
    condiciones: {
      enganchePct: 10,
      engancheNota: "A la firma de contrato",
      restoPct: 90,
      restoNota: "Crédito hipotecario a la escritura",
      mensualidades: null,
      formasPago: ["Crédito hipotecario"],
      promocionVigente: null,
      descuentoContado: null,
    },
    comercial: {
      buyerPersona: null,
      clienteIdeal: null,
      argumentos: [
        "Entrega marzo 2027 con esquema 10 / 90.",
        "Departamentos de 91 y 114 m² totales.",
      ],
      diferenciadores: [],
      objeciones: ["Las torres no cuentan con elevador, sólo escaleras."],
      comparables: ["Real Aurora", "Playa Encantada"],
      noDeberiaComprarlo: ["Cliente con movilidad reducida: no hay elevador."],
    },
    interna: {
      comisionPct: null,
      contactoComercial: null,
      convenioFirmado: null,
      dueDiligence: "validado",
      notasInternas: null,
      documentos: [
        { nombre: "Lista de precios oficial", tipo: "lista_precios", cargadoHaceDias: 4 },
        { nombre: "Brochure del desarrollo", tipo: "brochure", cargadoHaceDias: 12 },
      ],
    },
    validaciones: [
      { campo: "precio", validadoPor: "Jorge Díaz", haceDias: 2 },
      { campo: "disponibilidad", validadoPor: "Jorge Díaz", haceDias: 4 },
      { campo: "promocion", validadoPor: "Jorge Díaz", haceDias: 7 },
      { campo: "entrega", validadoPor: "Mariana Ruiz", haceDias: 50 },
      { campo: "comision", validadoPor: "Corporativo", haceDias: 20 },
    ],
  },
  {
    id: "real-aurora",
    nombre: "Real Aurora",
    plazaId: "riviera-maya",
    ciudad: "Playa del Carmen",
    zona: null,
    direccion: null,
    mapaUrl: null,
    tipo: "departamento",
    desarrollador: null,
    estatus: "publicado",
    entrega: "Mayo 2027",
    entregaIso: "2027-05",
    responsableId: "u-mariana",
    amenidades: ["Alberca", "Cancha de pádel"],
    aConsiderar: [],
    tipologias: [
      {
        id: "ra-2hab-n1",
        desarrolloId: "real-aurora",
        nombre: "Departamento 2 habitaciones · primer nivel",
        recamaras: 2,
        banos: 2.5,
        m2Construccion: 91.39,
        m2Terreno: null,
        estacionamientos: null,
        planoUrl: null,
        niveles: [
          { nombre: "Primer nivel", precioLista: 3655600, precioVenta: 3655600, disponibles: null },
        ],
      },
      {
        id: "ra-2hab-n2",
        desarrolloId: "real-aurora",
        nombre: "Departamento 2 habitaciones · segundo nivel",
        recamaras: 2,
        banos: 2.5,
        m2Construccion: 89.55,
        m2Terreno: null,
        estacionamientos: null,
        planoUrl: null,
        niveles: [
          { nombre: "Segundo nivel", precioLista: 3550000, precioVenta: 3550000, disponibles: null },
        ],
      },
    ],
    condiciones: {
      enganchePct: 30,
      engancheNota: "Al firmar contrato",
      restoPct: 70,
      restoNota: "Crédito hipotecario a la escritura",
      mensualidades: null,
      formasPago: ["Crédito hipotecario"],
      promocionVigente: null,
      descuentoContado: null,
    },
    comercial: {
      buyerPersona: null,
      clienteIdeal: null,
      argumentos: [
        "Dos habitaciones con dos baños y medio.",
        "El desarrollador tiene un proyecto anterior entregado en la zona.",
      ],
      diferenciadores: [],
      objeciones: [],
      comparables: ["Playa Park"],
      noDeberiaComprarlo: [],
    },
    interna: {
      comisionPct: null,
      contactoComercial: null,
      convenioFirmado: null,
      dueDiligence: "validado",
      notasInternas: null,
      documentos: [
        { nombre: "Brochure del desarrollo", tipo: "brochure", cargadoHaceDias: 9 },
        { nombre: "Fotos del proyecto anterior", tipo: "otro", cargadoHaceDias: 9 },
      ],
    },
    validaciones: [
      { campo: "precio", validadoPor: "Mariana Ruiz", haceDias: 4 },
      { campo: "disponibilidad", validadoPor: "Mariana Ruiz", haceDias: 6 },
      { campo: "promocion", validadoPor: "Mariana Ruiz", haceDias: 12 },
      { campo: "entrega", validadoPor: "Mariana Ruiz", haceDias: 14 },
      { campo: "comision", validadoPor: "Corporativo", haceDias: 30 },
    ],
  },
  {
    id: "playa-encantada",
    nombre: "Playa Encantada",
    plazaId: "riviera-maya",
    ciudad: "Playa del Carmen",
    zona: null,
    direccion: null,
    mapaUrl: null,
    tipo: "departamento",
    desarrollador: null,
    estatus: "publicado",
    entrega: null,
    entregaIso: null,
    responsableId: "u-jorge",
    amenidades: [],
    aConsiderar: [],
    tipologias: [],
    condiciones: {
      enganchePct: null,
      engancheNota: null,
      restoPct: null,
      restoNota: null,
      mensualidades: null,
      formasPago: [],
      promocionVigente: null,
      descuentoContado: null,
    },
    comercial: {
      buyerPersona: null,
      clienteIdeal: null,
      argumentos: [],
      diferenciadores: [],
      objeciones: [],
      comparables: [],
      noDeberiaComprarlo: [],
    },
    interna: {
      comisionPct: null,
      contactoComercial: null,
      convenioFirmado: null,
      dueDiligence: "pendiente",
      notasInternas: null,
      documentos: [],
    },
    validaciones: [
      { campo: "precio", validadoPor: "Jorge Díaz", haceDias: 38 },
      { campo: "disponibilidad", validadoPor: "Jorge Díaz", haceDias: 38 },
    ],
  },
  {
    id: "aukena",
    nombre: "Aukena",
    plazaId: "riviera-maya",
    ciudad: "Playa del Carmen",
    zona: null,
    direccion: null,
    mapaUrl: null,
    tipo: "departamento",
    desarrollador: null,
    estatus: "publicado",
    entrega: null,
    entregaIso: null,
    responsableId: "u-jorge",
    amenidades: [],
    aConsiderar: [],
    tipologias: [],
    condiciones: {
      enganchePct: null,
      engancheNota: null,
      restoPct: null,
      restoNota: null,
      mensualidades: null,
      formasPago: [],
      promocionVigente: null,
      descuentoContado: null,
    },
    comercial: {
      buyerPersona: null,
      clienteIdeal: null,
      argumentos: [],
      diferenciadores: [],
      objeciones: [],
      comparables: [],
      noDeberiaComprarlo: [],
    },
    interna: {
      comisionPct: null,
      contactoComercial: null,
      convenioFirmado: null,
      dueDiligence: "en_proceso",
      notasInternas: null,
      documentos: [],
    },
    validaciones: [
      { campo: "precio", validadoPor: "Jorge Díaz", haceDias: 21 },
      { campo: "disponibilidad", validadoPor: "Jorge Díaz", haceDias: 21 },
      { campo: "entrega", validadoPor: "Jorge Díaz", haceDias: 21 },
    ],
  },
  {
    id: "cascatta",
    nombre: "Cascatta",
    plazaId: "puebla",
    ciudad: "Puebla",
    zona: null,
    direccion: null,
    mapaUrl: null,
    tipo: "casa",
    desarrollador: null,
    estatus: "aprobado",
    entrega: null,
    entregaIso: null,
    responsableId: "u-luis",
    amenidades: [],
    aConsiderar: [],
    tipologias: [],
    condiciones: {
      enganchePct: null,
      engancheNota: null,
      restoPct: null,
      restoNota: null,
      mensualidades: null,
      formasPago: [],
      promocionVigente: null,
      descuentoContado: null,
    },
    comercial: {
      buyerPersona: null,
      clienteIdeal: null,
      argumentos: [],
      diferenciadores: [],
      objeciones: [],
      comparables: ["Parque Toscana", "Lomas de Angelópolis"],
      noDeberiaComprarlo: [],
    },
    interna: {
      comisionPct: null,
      contactoComercial: null,
      convenioFirmado: null,
      dueDiligence: "validado",
      notasInternas: null,
      documentos: [],
    },
    validaciones: [
      { campo: "precio", validadoPor: "Luis Ortega", haceDias: 6 },
      { campo: "disponibilidad", validadoPor: "Luis Ortega", haceDias: 6 },
      { campo: "comision", validadoPor: "Corporativo", haceDias: 10 },
    ],
  },
  {
    id: "parque-toscana",
    nombre: "Parque Toscana",
    plazaId: "puebla",
    ciudad: "Puebla",
    zona: null,
    direccion: null,
    mapaUrl: null,
    tipo: "casa",
    desarrollador: null,
    estatus: "revision",
    entrega: null,
    entregaIso: null,
    responsableId: "u-luis",
    amenidades: [],
    aConsiderar: [],
    tipologias: [],
    condiciones: {
      enganchePct: null,
      engancheNota: null,
      restoPct: null,
      restoNota: null,
      mensualidades: null,
      formasPago: [],
      promocionVigente: null,
      descuentoContado: null,
    },
    comercial: {
      buyerPersona: null,
      clienteIdeal: null,
      argumentos: [],
      diferenciadores: [],
      objeciones: [],
      comparables: [],
      noDeberiaComprarlo: [],
    },
    interna: {
      comisionPct: null,
      contactoComercial: null,
      convenioFirmado: null,
      dueDiligence: "pendiente",
      notasInternas: null,
      documentos: [],
    },
    validaciones: [{ campo: "precio", validadoPor: "Luis Ortega", haceDias: 51 }],
  },
];

export const usuarios: Usuario[] = [
  {
    id: "u-jorge",
    nombre: "Jorge Díaz",
    correo: "jorge.diaz@casacruz.mx",
    rol: "cerrador",
    plazasCertificadas: ["riviera-maya"],
    plazasEnProgreso: ["puebla"],
    activo: true,
    ultimoAcceso: "hoy 08:12",
    desarrollosACargo: 10,
  },
  {
    id: "u-mariana",
    nombre: "Mariana Ruiz",
    correo: "mariana.ruiz@casacruz.mx",
    rol: "cerrador",
    plazasCertificadas: ["riviera-maya"],
    plazasEnProgreso: [],
    activo: true,
    ultimoAcceso: "hoy 07:40",
    desarrollosACargo: 9,
  },
  {
    id: "u-luis",
    nombre: "Luis Ortega",
    correo: "luis.ortega@casacruz.mx",
    rol: "cerrador",
    plazasCertificadas: ["puebla"],
    plazasEnProgreso: [],
    activo: false,
    ultimoAcceso: "hace 9 días",
    desarrollosACargo: 11,
  },
  {
    id: "u-gerente-rm",
    nombre: "[GERENTE RIVIERA MAYA]",
    correo: "[CORREO]",
    rol: "gerente",
    plazasCertificadas: ["riviera-maya"],
    plazasEnProgreso: [],
    activo: true,
    ultimoAcceso: "ayer 19:02",
    desarrollosACargo: 0,
  },
  {
    id: "u-corp",
    nombre: "[DIRECCIÓN CASA CRUZ]",
    correo: "[CORREO]",
    rol: "corporativo",
    plazasCertificadas: ["riviera-maya", "puebla", "queretaro"],
    plazasEnProgreso: [],
    activo: true,
    ultimoAcceso: "hoy 09:55",
    desarrollosACargo: 0,
  },
];

export const clientes: Cliente[] = [
  {
    id: "c-berenice-fabian",
    nombre: "Berenice Gutiérrez y Fabián Dávila",
    correo: null,
    telefono: null,
    ciudadResidencia: null,
    presupuestoMin: 2500000,
    presupuestoMax: 3600000,
    recamaras: "2 o 3",
    objetivo: "vivienda",
    plazasInteres: ["riviera-maya"],
    kommoLeadId: "4821",
    kommoEtapa: "Propuesta enviada",
    notas:
      "Buscan departamento para vivir, financiado con crédito hipotecario. Les preocupa la entrega y quieren entender bien el esquema de pago antes de decidir.",
    actividad: [
      { fecha: "18 sep", texto: "Jorge generó la propuesta con Playa Park, Real Aurora y Cascatta." },
      { fecha: "17 sep", texto: "Llamada de seguimiento: piden comparar el esquema de pago." },
      { fecha: "05 sep", texto: "Abrieron el análisis previo desde el celular." },
      { fecha: "02 sep", texto: "Se envió el análisis de propiedades de Playa del Carmen." },
      { fecha: "28 ago", texto: "Lead creado en Kommo desde campaña de Meta." },
    ],
  },
  {
    id: "c-lead-4903",
    nombre: "[NOMBRE EN KOMMO] · lead 4903",
    correo: null,
    telefono: null,
    ciudadResidencia: "Houston, TX",
    presupuestoMin: 3000000,
    presupuestoMax: 4000000,
    recamaras: "3",
    objetivo: "vivienda",
    plazasInteres: ["riviera-maya", "puebla"],
    kommoLeadId: "4903",
    kommoEtapa: "Calificado",
    notas:
      "Familia mexicana viviendo en Houston. Quieren regresar a México y están comparando Playa del Carmen contra Puebla.",
    actividad: [
      { fecha: "17 sep", texto: "Primera llamada: definió presupuesto y plazas de interés." },
      { fecha: "15 sep", texto: "Lead creado en Kommo desde campaña de Meta (público EE. UU.)." },
    ],
  },
  {
    id: "c-lead-4877",
    nombre: "[NOMBRE EN KOMMO] · lead 4877",
    correo: null,
    telefono: null,
    ciudadResidencia: null,
    presupuestoMin: 2000000,
    presupuestoMax: 2800000,
    recamaras: "2",
    objetivo: "inversion",
    plazasInteres: ["riviera-maya"],
    kommoLeadId: "4877",
    kommoEtapa: "Sin respuesta",
    notas: "Busca departamento para rentar. No contesta desde el 11 de septiembre.",
    actividad: [
      { fecha: "11 sep", texto: "Se envió la ficha de Real Aurora por WhatsApp." },
      { fecha: "09 sep", texto: "Lead creado en Kommo." },
    ],
  },
];

export const propuestas: Propuesta[] = [
  {
    id: "p-001",
    slug: "berenice-fabian",
    clienteId: "c-berenice-fabian",
    usuarioId: "u-jorge",
    formato: "web",
    opciones: {
      esquemaPagos: true,
      costosCierre: true,
      comparativo: true,
      videoInstitucional: false,
      mapa: true,
    },
    items: [
      {
        desarrolloId: "playa-park",
        tipologiaId: "pp-3hab",
        nivel: "Tercer nivel",
        precioCongelado: 3070000,
        razon:
          "Es la única opción de tres habitaciones que se mantiene dentro de su presupuesto, y el enganche de 10% les permite conservar liquidez para el trámite del crédito.",
      },
      {
        desarrolloId: "real-aurora",
        tipologiaId: "ra-2hab-n2",
        nivel: "Segundo nivel",
        precioCongelado: 3550000,
        razon:
          "Dos habitaciones con dos baños y medio. Pide un enganche mayor, pero el desarrollador ya tiene un proyecto entregado en la zona.",
      },
      {
        desarrolloId: "cascatta",
        tipologiaId: "",
        nivel: null,
        precioCongelado: null,
        razon: null,
      },
    ],
    creadaEl: "18 septiembre 2026",
    enviadaEl: "18 sep 2026 · 11:20",
    estado: "enviada",
    vistas: 0,
    kommoLeadId: "4821",
  },
  {
    id: "p-002",
    slug: "lead-4903",
    clienteId: "c-lead-4903",
    usuarioId: "u-jorge",
    formato: "web",
    opciones: {
      esquemaPagos: true,
      costosCierre: false,
      comparativo: true,
      videoInstitucional: true,
      mapa: true,
    },
    items: [
      {
        desarrolloId: "playa-park",
        tipologiaId: "pp-3hab",
        nivel: "Planta baja",
        precioCongelado: 3500000,
        razon:
          "Tres habitaciones en planta baja, sin escaleras, para una familia que regresa a México con hijos pequeños.",
      },
      {
        desarrolloId: "real-aurora",
        tipologiaId: "ra-2hab-n1",
        nivel: "Primer nivel",
        precioCongelado: 3655600,
        razon: "Torre con amenidades completas y entrega dos meses después.",
      },
    ],
    creadaEl: "17 septiembre 2026",
    enviadaEl: "17 sep 2026 · 18:40",
    estado: "vista",
    vistas: 7,
    kommoLeadId: "4903",
  },
  {
    id: "p-003",
    slug: "lead-4877",
    clienteId: "c-lead-4877",
    usuarioId: "u-mariana",
    formato: "ficha",
    opciones: {
      esquemaPagos: true,
      costosCierre: false,
      comparativo: false,
      videoInstitucional: false,
      mapa: false,
    },
    items: [
      {
        desarrolloId: "real-aurora",
        tipologiaId: "ra-2hab-n2",
        nivel: "Segundo nivel",
        precioCongelado: 3550000,
        razon: "Opción de dos habitaciones para renta vacacional.",
      },
    ],
    creadaEl: "11 septiembre 2026",
    enviadaEl: "11 sep 2026 · 09:15",
    estado: "sin_respuesta",
    vistas: 2,
    kommoLeadId: "4877",
  },
];

export const cambios: Cambio[] = [
  {
    id: "ch-1",
    desarrolloId: "playa-park",
    desarrolloNombre: "Playa Park",
    campo: "Precio · 3 hab · planta baja",
    valorAnterior: "$3,450,000",
    valorNuevo: "$3,500,000",
    usuario: "Jorge Díaz",
    fecha: "14 sep 2026 · 12:43",
    fuente: "lista_precios",
    evidencia: "lista-precios-playa-park-sep-2026.pdf",
    estado: "publicado",
  },
  {
    id: "ch-2",
    desarrolloId: "playa-park",
    desarrolloNombre: "Playa Park",
    campo: "Nota comercial · torres sin elevador",
    valorAnterior: "(vacío)",
    valorNuevo: "Publicada",
    usuario: "Jorge Díaz",
    fecha: "12 sep 2026 · 09:10",
    fuente: "llamada",
    evidencia: null,
    estado: "publicado",
  },
  {
    id: "ch-3",
    desarrolloId: "playa-park",
    desarrolloNombre: "Playa Park",
    campo: "Fecha de entrega",
    valorAnterior: "Enero 2027",
    valorNuevo: "Marzo 2027",
    usuario: "Mariana Ruiz",
    fecha: "02 sep 2026 · 17:26",
    fuente: "correo",
    evidencia: "correo-desarrollador-02-sep.eml",
    estado: "publicado",
  },
  {
    id: "ch-4",
    desarrolloId: "playa-park",
    desarrolloNombre: "Playa Park",
    campo: "Comisión autorizada",
    valorAnterior: "[ANTERIOR]",
    valorNuevo: "[NUEVA]",
    usuario: "Jorge Díaz",
    fecha: "18 sep 2026 · 10:24",
    fuente: "convenio",
    evidencia: "convenio-playa-park.pdf",
    estado: "pendiente",
  },
  {
    id: "ch-5",
    desarrolloId: "real-aurora",
    desarrolloNombre: "Real Aurora",
    campo: "Fecha contractual de entrega",
    valorAnterior: "Mayo 2027",
    valorNuevo: "Julio 2027",
    usuario: "Mariana Ruiz",
    fecha: "17 sep 2026 · 18:05",
    fuente: "correo",
    evidencia: "correo-desarrollador-17-sep.eml",
    estado: "pendiente",
  },
  {
    id: "ch-6",
    desarrolloId: "cascatta",
    desarrolloNombre: "Cascatta",
    campo: "Esquema de pago especial",
    valorAnterior: "[ANTERIOR]",
    valorNuevo: "[NUEVO]",
    usuario: "Luis Ortega",
    fecha: "16 sep 2026 · 13:12",
    fuente: "llamada",
    evidencia: null,
    estado: "pendiente",
  },
];

export const novedades = [
  {
    fecha: "18 SEP",
    titulo: "Playa Park subió precio de 3 hab",
    detalle: "Planta baja $3,450,000 → $3,500,000. Fuente: lista oficial.",
  },
  {
    fecha: "16 SEP",
    titulo: "Real Aurora cambió esquema",
    detalle: "Ahora 30% de enganche al firmar contrato.",
  },
  {
    fecha: "15 SEP",
    titulo: "Cascatta pasó a aprobado",
    detalle: "Due diligence validado por corporativo.",
  },
  {
    fecha: "12 SEP",
    titulo: "Nota nueva en Playa Park",
    detalle: "Las torres no cuentan con elevador, sólo escaleras.",
  },
];
